default_platform(:ios)

DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]
DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]
APP_STORE_CONNECT_TEAM_ID = ENV["APP_STORE_CONNECT_TEAM_ID"]
DEVELOPER_APP_IDENTIFIER_RECEIVE_SHARE = "dev.golenia.foodly.ReceiveShare"

platform :ios do
  lane :closed_beta do
    setup_ci

    match(
      type: 'appstore',
      app_identifier: ["#{DEVELOPER_APP_IDENTIFIER}", "#{DEVELOPER_APP_IDENTIFIER_RECEIVE_SHARE}"],
      git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]),
      readonly: true
    )

    gym(
      configuration: "Release",
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      cloned_source_packages_path: "../build/ios/SourcePackages",
      export_method: "app-store"
    )

    pilot(
      apple_id: "#{DEVELOPER_APP_ID}",
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "./Runner.ipa",
      itc_provider: "#{APP_STORE_CONNECT_TEAM_ID}"
    )
  end
end
