name: Analyze app

on:
  pull_request:
    branches:
      - 'master'

jobs:
  
  build:
    name: Analyze flutter code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # or: 'dev' or 'beta'
    - name: Get Dependencies
      run: flutter pub get
    - name: Create dummy secrets
      run: sh ./.github/scripts/create_dummy_secrets.sh
        env:
          DUMMY_SECRETS: ${{ secrets.DUMMY_SECRETS }}
    - name: Code analyze
      run: flutter analyze --no-fatal-infos --no-fatal-warnings