name: Analyze app

on:
  pull_request:
    branches:
      - "master"

jobs:
  build:
    name: Analyze Flutter code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.6"
      - name: Get dependencies
        run: flutter pub get
      - name: Create dummy secrets
        run: sh ./.github/scripts/create_dummy_secrets.sh
        env:
          SECRETS_ENV_DUMMY: ${{ secrets.SECRETS_ENV_DUMMY }}
      - name: Run Flutter build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze
        run: flutter analyze --no-fatal-infos
      - name: Test
        run: flutter test
