name: Deploy App

on:
  push:
    branches:
      - master

jobs:
  deploy_ios:
    name: iOS deployment TestFlight
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.3"
      - name: Get Flutter packages
        run: flutter pub get
      - name: Install GNU sed
        run: |
          brew install gnu-sed
      - name: Create general secrets
        run: sh ./.github/scripts/create_general_secrets.sh
        env:
          SECRETS_ENV: ${{ secrets.SECRETS_ENV }}
      - name: Create ios secrets
        run: sh ./.github/scripts/create_secret_files.sh
        env:
          GOOGLE_SERVICES_IOS: ${{ secrets.GOOGLE_SERVICES_IOS }}
      - name: Run Flutter build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Test
        run: flutter test
      - name: Set version to version in commit
        run: bash ./.github/scripts/update_version_ios.sh '${{ github.event.head_commit.message }}' '${{ github.run_number }}'
      - name: Build app
        run: flutter build ios --release --no-codesign
      - name: Deploy iOS Beta to TestFlight via Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: closed_beta
          subdirectory: ios
          # working-directory: ios
        env:
          APP_STORE_CONNECT_TEAM_ID: "${{ secrets.APP_STORE_CONNECT_TEAM_ID }}"
          DEVELOPER_APP_ID: "${{ secrets.DEVELOPER_APP_ID }}"
          DEVELOPER_APP_IDENTIFIER: "${{ secrets.DEVELOPER_APP_IDENTIFIER }}"
          DEVELOPER_PORTAL_TEAM_ID: "${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}"
          FASTLANE_APPLE_ID: "${{ secrets.FASTLANE_APPLE_ID }}"
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: "${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}"
          MATCH_PASSWORD: "${{ secrets.MATCH_PASSWORD }}"
          GIT_AUTHORIZATION: "${{ secrets.GIT_AUTHORIZATION }}"
          PROVISIONING_PROFILE_SPECIFIER: "${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}"
          FASTLANE_PASSWORD: "${{ secrets.TEMP_KEYCHAIN_PASSWORD }}"
          TEMP_KEYCHAIN_USER: "${{ secrets.TEMP_KEYCHAIN_USER }}"
      - name: Notify on failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            FAILED iOS deployment!
            Commit: ${{ github.event.commits[0].message }}
            Action: https://github.com/LucasG04/foodly_app/actions/runs/${{ github.run_id }}
  deploy_android:
    name: Android deployment Internal
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Setup Rubya
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.3"
          bundler-cache: true
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Create general secrets
        run: sh ./.github/scripts/create_general_secrets.sh
        env:
          SECRETS_ENV: ${{ secrets.SECRETS_ENV }}
      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_keys.sh
        env:
          ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
      - name: Run Flutter build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Test
        run: flutter test
      - name: Set version to version in commit
        run: bash ./.github/scripts/update_version.sh '${{ github.event.head_commit.message }}' '${{ github.run_number }}'
      - name: Build the AAB
        run: flutter build appbundle
      - name: Run Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: internal
          subdirectory: android
          # working-directory: android
      - name: Notify on failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            FAILED Android deployment!
            Commit: ${{ github.event.commits[0].message }}
            Action: https://github.com/LucasG04/foodly_app/actions/runs/${{ github.run_id }}
